name: scandit_flutter_datacapture_barcode
description: This plugin implements the barcode capture capabilities of the Scandit Data Capture SDK. It supports reading a large number of different barcode symbologies.
version: 8.0.0
homepage: https://scandit.com



environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_core:
    '>=8.0.0 <8.0.1'
  meta: ^1.3.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4
  flutter_lints: 6.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.scandit.datacapture.flutter.barcode
        pluginClass: ScanditFlutterDataCaptureBarcodeProxyPlugin
      ios:
        pluginClass: ScanditFlutterDataCaptureBarcode
